overrides:
  files: 'src/**/__tests__/*'
  env:
    jest: true

env:
  node: true
  es6: true

parser: babel-eslint

extends:
  - eslint:recommended
  - plugin:prettier/recommended

parserOptions:
  ecmaFeatures:
    sourceType: module
